# Generated by Django 3.2.10 on 2021-12-31 00:23

import api.utils.autodatetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cah'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', api.utils.autodatetime.AutoDateTimeField(editable=False)),
                ('round', models.SmallIntegerField(default=0, editable=False, help_text='game round', validators=[django.core.validators.MinValueValidator(1, message='value should be >= 1 and <= 50'), django.core.validators.MaxValueValidator(50, message='value should be >= 1 and <= 50')])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blackcard')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', api.utils.autodatetime.AutoDateTimeField(editable=False)),
                ('round', models.SmallIntegerField(default=0, editable=False, help_text='game round', validators=[django.core.validators.MinValueValidator(1, message='value should be >= 1 and <= 50'), django.core.validators.MaxValueValidator(50, message='value should be >= 1 and <= 50')])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.whitecard')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
        ),
        migrations.AddConstraint(
            model_name='availablequestion',
            constraint=models.UniqueConstraint(fields=('game', 'card', 'round'), name='unique_available_question_player_game_round'),
        ),
        migrations.AddConstraint(
            model_name='availableanswer',
            constraint=models.UniqueConstraint(fields=('game', 'card', 'round'), name='unique_available_answer_player_game_round'),
        ),
    ]
