# Generated by Django 3.2.10 on 2022-01-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cfh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcard',
            name='pick',
            field=models.CharField(choices=[(1, 'PICK_ONE'), (3, 'PICK_THREE'), (2, 'PICK_TWO')], default=1, max_length=10),
        ),
    ]
