# Generated by Django 3.2.9 on 2021-12-07 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_private'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invite',
            name='unique_user_invite_game',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='user',
        ),
        migrations.AddField(
            model_name='invite',
            name='uid',
            field=models.CharField(default=None, help_text='text allows 2-255 characters(alphabets and -,_,.,\',",space)', max_length=255, validators=[django.core.validators.MinLengthValidator(5, 'text allows 2-255 characters(alphabets and -,_,.,\',",space)'), django.core.validators.RegexValidator('^[A-Za-z]([\\w+|-|\\s|\\\'|\\"|\\.|!]?)+', 'text allows 2-255 characters(alphabets and -,_,.,\',",space)')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.CharField(help_text='text allows 2-255 characters(alphabets and -,_,.,\',",space)', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'text allows 2-255 characters(alphabets and -,_,.,\',",space)'), django.core.validators.RegexValidator('^[A-Za-z]([\\w+|-|\\s|\\\'|\\"|\\.|!]?)+', 'text allows 2-255 characters(alphabets and -,_,.,\',",space)')]),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(fields=('game', 'uid'), name='unique_uid_invite_game'),
        ),
    ]
