# Generated by Django 3.2.10 on 2022-01-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_game_num_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="selected",
            field=models.BooleanField(default=False),
        ),
    ]
