# Generated by Django 3.2.10 on 2022-01-01 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_answer_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(error_messages={'unique': 'You already used this password.'}, help_text='password must have a minimum of 8 characters\npassword must have a maximum of 30 characters\npassword must have an uppercase character\npassword must have a lowercase character\npassword must have a numeric character\npassword must have a special characters', max_length=128, validators=[django.core.validators.RegexValidator('^.*(?=.{8,})((?=.*[!@#$%^&*()\\-_=+{};:,<.>]){1})(?=.*\\d)((?=.*[a-z]){1})((?=.*[A-Z]){1}).*$', 'password must have a minimum of 8 characters\npassword must have a maximum of 30 characters\npassword must have an uppercase character\npassword must have a lowercase character\npassword must have a numeric character\npassword must have a special characters')], verbose_name='password'),
        ),
        migrations.AddIndex(
            model_name='password',
            index=models.Index(fields=['is_active'], name='api_passwor_is_acti_5e6ed6_idx'),
        ),
        migrations.AddConstraint(
            model_name='password',
            constraint=models.UniqueConstraint(fields=('user', 'password'), name='unique_user_password'),
        ),
    ]
