# Generated by Django 3.2.10 on 2022-01-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20220101_1335"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="question",
            name="unique_question_player_game_round",
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("game", "player", "card", "round"),
                name="unique_question_player_game_card_round",
            ),
        ),
    ]
