# Generated by Django 3.2.9 on 2021-12-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_invite_revoked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='expires_at',
        ),
    ]
