# Generated by Django 3.2.9 on 2021-12-14 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_invite_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.provider'),
        ),
    ]
