# Generated by Django 3.2.9 on 2021-12-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profile_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
