# Generated by Django 3.2.10 on 2022-01-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0015_edit_solarschedule_events_choices"),
        ("api", "0013_alter_game_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="task",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
