# Generated by Django 3.2.10 on 2022-01-05 02:25

import api.utils.autodatetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_game_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Czar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    api.utils.autodatetime.AutoDateTimeField(editable=False),
                ),
                (
                    "round",
                    models.SmallIntegerField(
                        default=0,
                        editable=False,
                        help_text="game round",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="value should be >= 1 and <= 50"
                            ),
                            django.core.validators.MaxValueValidator(
                                50, message="value should be >= 1 and <= 50"
                            ),
                        ],
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_czar",
                        to="api.player",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="czar",
            constraint=models.UniqueConstraint(
                fields=("game", "player", "round"), name="unique_czar_game_player_round"
            ),
        ),
    ]
