# Generated by Django 3.2.10 on 2022-01-05 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_auto_20220105_0225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="czar",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="czar_set",
                to="api.player",
            ),
        ),
    ]
