# Generated by Django 3.2.10 on 2022-01-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0015_edit_solarschedule_events_choices"),
        ("api", "0016_alter_czar_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="czar",
            name="game",
        ),
        migrations.RemoveField(
            model_name="czar",
            name="player",
        ),
        migrations.RemoveConstraint(
            model_name="player",
            name="unique_player_game_czar",
        ),
        migrations.RemoveIndex(
            model_name="player",
            name="api_player_czar_394727_idx",
        ),
        migrations.RemoveIndex(
            model_name="player",
            name="api_player_score_f8b261_idx",
        ),
        migrations.RemoveField(
            model_name="player",
            name="czar",
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("Awaiting Czar Answers", "GACA"),
                    ("Awaiting Czar Question", "GACQ"),
                    ("Awaiting Players", "GAP"),
                    ("Awaiting Player Answers", "GAPA"),
                    ("Game Canceled", "GC"),
                    ("Game Ended", "GE"),
                    ("Game Rounds Finished", "GRF"),
                    ("Game Started", "GS"),
                    ("Show Round Result", "GSRR"),
                ],
                default="Awaiting Players",
                max_length=23,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="task",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.DeleteModel(
            name="Czar",
        ),
    ]
