# Generated by Django 2.2.9 on 2020-01-30 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'data-migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='text allows 5-255 characters(alphabets and -,_,?,\',",space)', max_length=128, validators=[django.core.validators.MinLengthValidator(5, 'text allows 5-255 characters(alphabets and -,_,?,\',",space)'), django.core.validators.RegexValidator('^.*(?=.{8,})((?=.*[!@#$%^&*()\\-_=+{};:,<.>]){1})(?=.*\\d)((?=.*[a-z]){1})((?=.*[A-Z]){1}).*$', 'text allows 5-255 characters(alphabets and -,_,?,\',",space)')], verbose_name='password'),
        ),
    ]
