# Generated by Django 2.2.9 on 2020-01-21 02:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('cfh', 'cards for humanity'), ('cah', 'cards against humanity')], default='cfh', max_length=3)),
                ('round_time', models.SmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)])),
                ('rounds', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)])),
                ('num_players', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(8)])),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hint',
        ),
        migrations.AddField(
            model_name='question',
            name='card_type',
            field=models.CharField(choices=[(1, 'pick1'), (2, 'pick2')], default='pick1', max_length=5),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'answer allows 2-255 characters(alphabets and -,_,.,\',",space)'), django.core.validators.RegexValidator('^[A-Za-z]([\\w+|-|\\s|\\\'|\\"|\\.]?)+', 'answer allows 2-255 characters(alphabets and -,_,.,\',",space)')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'question allows 5-255 characters(alphabets and -,_,?,\',",space)'), django.core.validators.RegexValidator('^[A-Za-z]([\\w+|-|\\s|\\\'|\\"|\\?]?)+', 'question allows 5-255 characters(alphabets and -,_,?,\',",space)')]),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('czar', models.BooleanField(default=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game_id', 'player_id')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='czar_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Player'),
        ),
    ]
