# Generated by Django 2.2.9 on 2020-01-21 06:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200121_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='czar_id',
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(help_text='answer allows 2-255 characters(alphabets and -,_,.,\',",space)', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'answer allows 2-255 characters(alphabets and -,_,.,\',",space)'), django.core.validators.RegexValidator('^[A-Za-z]([\\w+|-|\\s|\\\'|\\"|\\.]?)+', 'answer allows 2-255 characters(alphabets and -,_,.,\',",space)')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='round_time',
            field=models.SmallIntegerField(default=10, help_text='seconds', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='question allows 5-255 characters(alphabets and -,_,?,\',",space)', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'question allows 5-255 characters(alphabets and -,_,?,\',",space)'), django.core.validators.RegexValidator('^[A-Za-z]([\\w+|-|\\s|\\\'|\\"|\\?]?)+', 'question allows 5-255 characters(alphabets and -,_,?,\',",space)')]),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game', 'player')},
        ),
    ]
