# Generated by Django 3.2.8 on 2021-10-20 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211018_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_players',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='rounds',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
