# Generated by Django 3.2.9 on 2021-11-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
