# Generated by Django 2.2.9 on 2020-01-21 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200121_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='game_type',
            field=models.CharField(choices=[('cfh', 'cards for humanity'), ('cah', 'cards against humanity')], default='cfh', max_length=3),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(help_text='answer allows 2-255 characters(alphabets and -,_,.,\',",space)', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'answer allows 2-255 characters(alphabets and -,_,.,\',",space)'), django.core.validators.RegexValidator('^[A-Za-z]([\\w+|-|\\s|\\\'|\\"|\\.|!]?)+', 'answer allows 2-255 characters(alphabets and -,_,.,\',",space)')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='card_type',
            field=models.CharField(choices=[('1', 'pick1'), ('2', 'pick2')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='question allows 5-255 characters(alphabets and -,_,?,\',",space)', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'question allows 5-255 characters(alphabets and -,_,?,\',",space)'), django.core.validators.RegexValidator('^[A-Za-z]([\\w+|-|\\s|\\\'|\\"|\\?|!]?)+', 'question allows 5-255 characters(alphabets and -,_,?,\',",space)')]),
        ),
    ]
