# Generated by Django 3.2.9 on 2021-12-03 04:56

from django.db import migrations, models
import pgtrigger.core


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_player_avatar"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="game",
            name="unique_game_status",
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                condition=pgtrigger.core.Q(("status", "Awaiting Players")),
                fields=("creator",),
                name="unique_game_status",
            ),
        ),
    ]
