# Generated by Django 2.2.9 on 2020-01-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200121_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('AP', 'Awaiting Players'), ('AC', 'Awaiting Czar'), ('GS', 'Game Started'), ('GE', 'Game Ended')], default='cc', max_length=3),
        ),
    ]
