# Generated by Django 3.2.8 on 2021-10-24 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211024_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='num_players',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='no of players', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
