# Generated by Django 3.2.9 on 2021-11-18 17:38

import api.models.verification_code
import api.utils.autodatetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackcard',
            name='rating',
            field=models.CharField(choices=[('Normal', 'Normal')], default='Normal', max_length=10),
        ),
        migrations.AddField(
            model_name='whitecard',
            name='rating',
            field=models.CharField(choices=[('Normal', 'Normal')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='blackcard',
            name='updated_at',
            field=api.utils.autodatetime.AutoDateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Awaiting Players', 'Gap'), ('Awaiting Czar', 'Gac'), ('Game Started', 'Gs'), ('Game Ended', 'Ge')], default='Awaiting Players', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='updated_at',
            field=api.utils.autodatetime.AutoDateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='password',
            name='updated_at',
            field=api.utils.autodatetime.AutoDateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='updated_at',
            field=api.utils.autodatetime.AutoDateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=api.utils.autodatetime.AutoDateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='updated_at',
            field=api.utils.autodatetime.AutoDateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=api.utils.autodatetime.AutoDateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='whitecard',
            name='updated_at',
            field=api.utils.autodatetime.AutoDateTimeField(editable=False),
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', api.utils.autodatetime.AutoDateTimeField(editable=False)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='verification code', unique=True)),
                ('expires_at', models.DateTimeField(editable=False, help_text='code expiry datetime', validators=[django.core.validators.MinValueValidator(limit_value=api.models.verification_code.VerificationCode.expiry_date)])),
                ('previous', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.verificationcode')),
                ('provider', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
