# Generated by Django 3.2.9 on 2021-12-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20211203_0456"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                fields=("user", "game"), name="unique_player_game"
            ),
        ),
    ]
