# Generated by Django 3.2.9 on 2021-12-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211209_1511'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='provider',
            name='api_provider_email_or_phone',
        ),
    ]
