# Generated by Django 3.2.9 on 2021-12-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_player_unique_player_game"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                condition=models.Q(("czar", True)),
                fields=("game",),
                name="unique_player_game_czar",
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                fields=("game", "avatar"), name="unique_player_game_avatar"
            ),
        ),
    ]
