# Generated by Django 3.2.8 on 2021-11-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211106_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winners', to='api.user'),
            preserve_default=False,
        ),
    ]
