# Generated by Django 3.2.9 on 2021-12-03 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20211203_1649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_set",
                to="api.game",
            ),
        ),
    ]
