# Generated by Django 3.2.9 on 2021-12-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_provider_last_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
