# Generated by Django 3.2.9 on 2021-12-03 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_player_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="num_players",
            field=models.PositiveSmallIntegerField(
                default=1,
                editable=False,
                help_text="no of players",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="value should be >= 1 and <= 9"
                    ),
                    django.core.validators.MaxValueValidator(
                        9, message="value should be >= 1 and <= 9"
                    ),
                ],
            ),
        ),
    ]
