# Generated by Django 3.2.9 on 2021-12-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_game_num_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
