# Generated by Django 3.2.9 on 2021-12-05 07:18

import api.utils.autodatetime
import api.utils.functions
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_auto_20211205_0715"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    api.utils.autodatetime.AutoDateTimeField(editable=False),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        editable=False,
                        help_text="invite expiry datetime",
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=api.utils.functions.expiry_date_min
                            )
                        ],
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="invite",
            constraint=models.UniqueConstraint(
                fields=("game", "user"), name="unique_user_invite_game"
            ),
        ),
    ]
