# Generated by Django 3.2.9 on 2021-12-05 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_auto_20211205_0718"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner",
                to="api.player",
            ),
        ),
    ]
