class GraphQLErrors:
    """Constant strings used to represent graphql errors to the client."""

    NOT_AUTHORIZED = "NOT_AUTHORIZED"
    NOT_VERIFIED = "NOT_VERIFIED"
    # Validation errors are returned all at once (using GraphQL "extensions")
    VALIDATION_ERRORS = "VALIDATION_ERRORS"

    USER_ACTIVATION_RESEND__ALREADY_ACTIVATED = (
        "USER_ACTIVATION_RESEND__ALREADY_ACTIVATED"
    )

    USER_ACTIVATE__CODE_INVALID = "USER_ACTIVATE__CODE_INVALID"
    USER_ACTIVATE__CODE_EXPIRE = "USER_ACTIVATE__CODE_EXPIRE"
    USER_ACTIVATE__CODE_INVALIDATED = "USER_ACTIVATE__CODE_INVALIDATED"
    USER_ACTIVATE__CODE_USED_ALREADY = "USER_ACTIVATE__CODE_USED_ALREADY"

    USER_PASSWORD_CHANGE__INVALID_CREDENTIALS = (
        "USER_PASSWORD_CHANGE__INVALID_CREDENTIALS"
    )
    USER_PASSWORD_CHANGE__PASSWORD_INVALID = "USER_PASSWORD_CHANGE__PASSWORD_INVALID"
    USER_PASSWORD_CHANGE__PASSWORD_SAME = "USER_PASSWORD_CHANGE__PASSWORD_SAME"
    USER_PASSWORD_CHANGE__PASSWORD_WEAK = "USER_PASSWORD_CHANGE__PASSWORD_WEAK"

    USER_PASSWORD_RESET__CODE_EXPIRED = "USER_PASSWORD_RESET__CODE_EXPIRED"
    USER_PASSWORD_RESET__CODE_INVALID = "USER_PASSWORD_RESET__CODE_INVALID"
    USER_PASSWORD_RESET__CODE_INVALIDATED = "USER_PASSWORD_RESET__CODE_INVALIDATED"
    USER_PASSWORD_RESET__CODE_USED_ALREADY = "USER_PASSWORD_RESET__CODE_USED_ALREADY"
    USER_PASSWORD_RESET__PASSWORD_INVALID = "USER_PASSWORD_RESET__PASSWORD_INVALID"
    USER_PASSWORD_RESET__PASSWORD_SAME = "USER_PASSWORD_RESET__PASSWORD_SAME"
    USER_PASSWORD_RESET__PASSWORD_WEAK = "USER_PASSWORD_RESET__PASSWORD_WEAK"

    USER_SIGNIN__INACTIVE_USER = "USER_SIGNIN__INACTIVE_USER"
    USER_SIGNIN__INVALID_CREDENTIALS = "USER_SIGNIN__INVALID_CREDENTIALS"
    USER_SIGNIN__UNKNOWN_ERROR = "USER_SIGNIN__UNKNOWN_ERROR"
    USER_SIGNIN__UNVERIFIED_USER = "USER_SIGNIN__UNVERIFIED_USER"

    USER_SIGNUP__DUPLICATE_ACCOUNT = "USER_SIGNUP__DUPLICATE_ACCOUNT"
    USER_SIGNUP__INVALID_NAME = "USER_SIGNUP__INVALID_NAME"
    USER_SIGNUP__PASSWORD_INVALID = "USER_SIGNUP__PASSWORD_INVALID"
    USER_SIGNUP__PASSWORD_WEAK = "USER_SIGNUP__PASSWORD_WEAK"
